// Code generated by "stringer -type=MsgType -trimprefix=Msg"; DO NOT EDIT.

package control

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgError-0]
	_ = x[MsgSuccess-1]
	_ = x[MsgHostInit-2]
	_ = x[MsgHostInitResp-3]
	_ = x[MsgCtrlCh-4]
	_ = x[MsgAppCh-5]
	_ = x[MsgPing-6]
	_ = x[MsgPong-7]
	_ = x[MsgConnReq-8]
}

const _MsgType_name = "ErrorSuccessHostInitHostInitRespCtrlChAppChPingPongConnReq"

var _MsgType_index = [...]uint8{0, 5, 12, 20, 32, 38, 43, 47, 51, 58}

func (i MsgType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MsgType_index)-1 {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[idx]:_MsgType_index[idx+1]]
}
